
STAMPOPTS = -l 30,580 -s 24


EVTOL= "EV-TOL-Mailing-Lists.csv"

RACES=$(shell cat 2020.list)
RPC=$(addsuffix -rpc.pdf, ${RACES})
FR=$(addsuffix -fr.pdf, ${RACES})
ML=$(addsuffix -ml.pdf, ${RACES})

# 1. RACES         YYYYMMDD-Race
# 2.               YYYYMMDD-Race.csv        # csv for race, input for glabel3
# 3. FR            YYYYMMDD-Race-fr.pdf     # front, generated by glabel3
# 4. PC            YYYYMMDD-Race-pc.pdf     # rear postcards stamped with date
# 5. RPC           YYYYMMDD-Race-rpc.pdf    # rear postcards rotaged
# 6. ML            YYYYMMDD-Race-ml.pdf     # merged front and backs

# 2&3 - generate fronts
%.csv : ${EVTOL}
	./tolmail ${EVTOL} $@ 

%-fr.pdf: %.csv
	glabels-3-batch -o "$@" -i - admail1.glabels < $<

# 4&5 - copy, stamp and rotate the postcard file to create back
.PRECIOUS: %-pc.pdf
.INTERMEDIATE: %-rpc.pdf
%-pc.pdf: 
	echo $@ | sed -e 's/\(.*\)-\(.*\)-pc.pdf/\1 \2/' | \
	while read d r; do \
		echo race: $$r; \
		echo date: $$d; \
		echo date: $$(date -d $$d '+%A %B %d, %Y'); \
		cp -v postcards/$$r.pdf $@ || exit 1; \
		pdfstamp ${STAMPOPTS} $@ "$$(date -d $$d '+%A %B %d, %Y')"; \
	done

%-rpc.pdf: %-pc.pdf 
	pdftk A=$< cat A1east output $@


# 5 - merge front with back
%-ml.pdf : %-rpc.pdf %-fr.pdf
	./mergepdf $@ 
	rm -rv $<


all: ${ML}

rpc: ${RPC}

ml: ${ML}

test:
	@echo RACES: ${RACES}
	@echo EVTOL: ${EVTOL}
	@echo
	@echo PC: ${PC}
	@echo FR: ${FR}
	@echo ML: ${ML}

races: ${RACES}

${ML} :  ${EVTOL} Makefile 2020.list

${EVTOL} :

#%.csv : ${EVTOL}

%-bside.pdf: 
	pdf

clean:
	rm -rf tmp *.pdf* *20*.csv


